### ISSUE TITLE
Unable to build hugo site

### ISSUE THREAD

**Issue by kkarakk** [luizdepra/hugo-coder#553] opened 2021-04-04 06:14 UTC
i'm running the hugo quickstart, i've installed all the dependencies(windows) and have had success running the default ananke theme.  
i wanted to use **hugo-coder** theme  
i'm able to download and deploy the theme with default config.toml and ` theme = "hugo-coder"` no problem but   
this does not deploy the website as shown in the default demo site   

however when i customise config with the default config mentioned on [hugo-coder theme site]( https://github.com/luizdepra/hugo-coder/wiki/Configurations#complete-example) i get this error when running `hugo serve` or `hugo server -D` :
-------------------------------------------------
```
PS C:\Users\Asus\website\quickstart> hugo server -D
Start building sites …
ERROR 2021/04/04 11:42:44 render of "home" failed: "C:\Users\Asus\website\quickstart\themes\hugo-coder\layouts\_default\baseof.html:71:40": execute of template failed: template: index.html:71:40: executing "index.html" at <toCSS $cssOpts>: error calling toCSS: no Resource provided in transformation
ERROR 2021/04/04 11:42:44 render of "taxonomy" failed: "C:\Users\Asus\website\quickstart\themes\hugo-coder\layouts\_default\baseof.html:71:40": execute of template failed: template: _default/list.html:71:40: executing "_default/list.html" at <toCSS $cssOpts>: error calling toCSS: no Resource provided in transformation
ERROR 2021/04/04 11:42:44 render of "page" failed: "C:\Users\Asus\website\quickstart\themes\hugo-coder\layouts\_default\baseof.html:71:40": execute of template failed: template: posts/single.html:71:40: executing "posts/single.html" at <toCSS $cssOpts>: error calling toCSS: no Resource provided in transformation
ERROR 2021/04/04 11:42:44 render of "taxonomy" failed: "C:\Users\Asus\website\quickstart\themes\hugo-coder\layouts\_default\baseof.html:71:40": execute of template failed: template: _default/list.html:71:40: executing "_default/list.html" at <toCSS $cssOpts>: error calling toCSS: no Resource provided in transformation
Built in 45 ms
Error: Error building site: failed to render pages: render of "section" failed: "C:\Users\Asus\website\quickstart\themes\hugo-coder\layouts\_default\baseof.html:71:40": execute of template failed: template: posts/list.html:71:40: executing "posts/list.html" at <toCSS $cssOpts>: error calling toCSS: no Resource provided in transformation
```

-------------------------------------------------  

am i missing some dependency? i've tried installing hugo-extended but i get the same error with that

**Comment by luizdepra** [comment] 2021-04-07 13:11
Using hugo-extended should do the trick. Are you 100% right that you are using the extended version?

Try running `hugo version` and see if its returns something like this:
```
$ hugo version
Hugo Static Site Generator v0.79.0-1415EFDC/extended linux/amd64 BuildDate: 2020-11-27T09:16:17Z
```

Another thing, the wiki config example may be outdated. The `exampleSite/config.toml` is a better base example.

Also, what is quickstart?

**Comment by DiogoMCampos** [comment] 2021-04-14 20:12
I think the "issue" is that the example configuration includes `customSCSS = ["scss/custom.scss"]` and Hugo won't build the website if that file doesn't exist, throwing that error.

It's merely an example though, so I'm not sure it should be changed at all.

**Comment by clayliddell** [comment] 2021-04-17 02:10
I just ran into the same issue:

1. I installed hugo-extended.
2. Followed the instructions in the "Quick Start" section of the project's README.
3. Encountered the same errors as @kkarakk.
4. Found this issue.
5. Copied over the new/more-up-to-date config file from `exampleSite/config.toml` as @luizdepra suggested.
6. Everything started working! :tada:

**Comment by rowe-morehouse** [comment] 2021-04-20 21:19
> 6. Everything started working! 🎉

Your fix worked for me too, thanks!

**Comment by manu29d** [comment] 2021-05-22 16:24
> _Also, what is quickstart?_

I think they are referring to [this](https://github.com/luizdepra/hugo-coder/wiki/Quick-Start) or [this one](https://gohugo.io/getting-started/quick-start/)

**Comment by wuchengshi** [comment] 2021-06-29 07:37
$ hugo server -D
Start building sites …
hugo v0.84.1-4BD65E22 windows/amd64 BuildDate=2021-06-24T11:44:23Z VendorInfo=gohugoio
ERROR 2021/06/29 15:00:44 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": Get "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": dial tcp 157.240.2.36:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Built in 30072 ms
Error: Error building site: "D:\hugo\hugoblog\content\posts\rich-content.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.

why ?  i have no idea

**Comment by DiogoMCampos** [comment] 2021-06-29 08:36
> $ hugo server -D
> Start building sites …
> hugo v0.84.1-4BD65E22 windows/amd64 BuildDate=2021-06-24T11:44:23Z VendorInfo=gohugoio
> ERROR 2021/06/29 15:00:44 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": Get "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": dial tcp 157.240.2.36:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
> ignoreErrors = ["error-remote-getjson"]
> Built in 30072 ms
> Error: Error building site: "D:\hugo\hugoblog\content\posts\rich-content.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
> 
> why ? i have no idea

Are you able to access https://twitter.com? That looks like you aren't and that's what's causing that error.

**Comment by luizdepra** [comment] 2021-11-02 19:02
@acidwars, Are all your `custom*` configs empty? It seems hugo is not finding a SCSS file.

**Comment by carvalholeo** [comment] 2021-11-28 22:24
Hey guys, how are you?

I'm experiencing the same issue. I have noticed the problem occurs when I try to use `custom*` configs, at `config.toml`.

Before, until commit `6581e860bde43960e3b6362001f270cd2e9db178`, I was able to use this theme with those custom JS and CSS. So, when I did a `git pull` to the submodule (commit `263be7cebc84993e099d662181cd4e4c5e937111`), and tested, as @acidwars and @kkarakk, when I try to build or serve, I'm getting the exactly same error.

Below the info from my env:

Hugo version: `hugo v0.89.4-AB01BA6E windows/amd64 BuildDate=2021-11-17T08:24:09Z VendorInfo=gohugoio`
O.S.: Windows 11 21H2 Build 22000.348
Release: Stable
Architecture: x64

Error:
```shell
$ hugo serve
Start building sites … 
hugo v0.89.4-AB01BA6E windows/amd64 BuildDate=2021-11-17T08:24:09Z VendorInfo=gohugoio
ERROR 2021/11/28 19:21:58 render of "page" failed: "C:\Users\lcarv\dev\leocarvalho.dev\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/single.html:66:47: executing "_default/single.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/11/28 19:21:58 render of "home" failed: "C:\Users\lcarv\dev\leocarvalho.dev\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: index.html:66:47: executing "index.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/11/28 19:21:58 render of "page" failed: "C:\Users\lcarv\dev\leocarvalho.dev\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/single.html:66:47: executing "_default/single.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/11/28 19:21:58 render of "taxonomy" failed: "C:\Users\lcarv\dev\leocarvalho.dev\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink       
Error: Error building site: failed to render pages: render of "taxonomy" failed: "C:\Users\lcarv\dev\leocarvalho.dev\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
Built in 50 ms```

**Comment by juanignaciosl** [comment] 2021-12-05 21:45
After enabling a custom scss (`customSCSS = ["scss/custom.scss"]`) I got that error, but creating a non-empty file at `/assets/scss/custom.scss` and restarting worked for me.

**Comment by agate-pris** [comment] 2021-12-15 12:20
Thank you @juanignaciosl. I'm the same as you.

I think this error is caued by commit 1cdbe4f14a7ac93662ba45197a66be46164360be.

**Comment by luizdepra** [comment] 2021-12-16 14:49
I might have a clue about what is happening. After that commit, we started using the Hugo's Asset Pipeline to process all the custom CSS and JS. So, now we need to store these files inside the `assets` folder, as this theme does with its own SCSS and JS, and not inside `static`.

I need to update a documentation somewhere about that.

**Comment by carvalholeo** [comment] 2021-12-16 17:04
Hey @luizdepra , tks to answer!

I didn't understand. Do I need to move `assets` folder outside `static` folder? If so, it doesn't have worked for me. Could you provide more information or context about this?

I saw at some issue about hugo version needed, and even reinstalling with `hugo-extended`, I'm  yet getting the same error 😢

**Comment by luizdepra** [comment] 2021-12-16 17:32
@carvalholeo 
> I didn't understand. Do I need to move assets folder outside static folder?
Yes. The `assets` folder should be on the root folder of your site alongside the `static` folder. See this project code, we have both folders. Explaining a bit, you should use the `static` folder to store unprocessed content like images, and you'll only need to move the JS and (S)CSS files you use in the `custom*` configs to the `assets` folder.

> If so, it doesn't have worked for me.
Maybe the path in the `config*` options is wrong? You shouldn't need to put `assets` in the path. The path is relative to the `assets` folder. Example:
```
// should work, file at `assets/css/style.css`
customCSS = ["css/style.css"]

// should fail
customCSS = ["assets/css/style.css"]
```

> I saw at some issue about hugo version needed, and even reinstalling with hugo-extended, I'm yet getting the same error cry
I always recommend the use of `hugo-extended`. In some cases, it is not necessary, but in this one it is.

**Comment by luizdepra** [comment] 2021-12-16 22:18
Confirmed. It worked on my site. 

https://github.com/luizdepra/luizdepra.dev/tree/master/assets
https://github.com/luizdepra/luizdepra.dev/blob/master/config.toml#L31

**Comment by carvalholeo** [comment] 2021-12-16 23:22
Hey @luizdepra , thank you so much!

I tried this and worked so 😆 😆 

Thank you for your time and support on this project!

**Comment by agate-pris** [comment] 2022-01-07 09:35
It works on [my site](https://www.agate-pris.dev/) too (agate-pris/agate-pris.dev#54). Thank you @luizdepra !

**Comment by pqteru** [comment] 2022-01-18 04:56
It works! thank you @luizdepra , just move your files from `static` to the root `assets` folder.

**Comment by luizdepra** [comment] 2022-01-27 16:48
I think we can close this issue, right?

**Closed by luizdepra** 2022-01-27 16:48 UTC
