### ISSUE TITLE
replacement for forkawsome

### ISSUE THREAD

**Issue by b-reich** [luizdepra/hugo-coder#873] opened 2023-12-15 09:04 UTC
ForkAwsome will no longer receive an update and is looking for new maintainer. Unfortunately, newer icons are now missing.

https://github.com/ForkAwesome/Fork-Awesome
> ⚠️ This project has not had a release for ~2 years, and another release is not planned. Rather, this project will be archived by mid 2024 unless someone else takes over maintenance. This is because:
>>    The driving force for forking—to have a community run icon set—has not been realized. The site and font build processes are  broken. The source icon files need to be reworked or remade. The project focuses on icon fonts, despite icon fonts as a technology being outdated. Many other free icon sets now exist.

**Comment by lpar** [comment] 2023-12-24 03:15
Duplicate of #858

**Closed** 2023-12-24 21:06 UTC
